- name: Copy hosts file from artifacts to etc
  hosts: chroots
  tasks:
    - name: Copy hosts file from artifacts to etc
      ansible.builtin.copy:
        src: "{{ artifacts_root }}/hosts"
        dest: /etc/hosts
        owner: root
        group: root
        mode: "0644"
