- name: Install chrony
  hosts: chroots
  tasks:
    - name: Ensure chrony is installed
      apk:
        name: chrony
        state: present

    - name: Enable chronyd on boot
      command: rc-update add chronyd boot
      args:
        creates: /etc/runlevels/boot/chronyd

    - name: Set custom NTP servers
      lineinfile:
        path: /etc/chrony/chrony.conf
        regexp: "^pool"
        line: "pool pool.ntp.org iburst"
